title: Lim Hyunwoo
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://tanker0212.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: tanker0212
   twitter: 
   facebook: 
   email: tanker0212@gmail.com

google_analytics: "UA-58263416-1"
